# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/myint/autoflake
    rev: v1.7.6
    hooks:
    -   id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.1.0
    hooks:
    -   id: setup-cfg-fmt
