on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

name: Tests

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install -e .

    - name: Test
      run: python tests/runner.py
